Website/Website/Models/DiaDiem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Website.Models
{
    public class DiaDiem
    {
        [Key]
        public int ID { set; get; }
        [Display(Name = "Tên địa điểm")]
        [Required(ErrorMessage = "Nhập tên địa điểm!")]
        [StringLength(50, ErrorMessage = "Nội dung tối thiểu 10 kí tự!")]
        public string Ten { set; get; }
        [Display(Name = "Chủ đề")]
        public string ChuDe { set; get; }
        [Display(Name = "Chủ đề con")]
        public string ChuDeCon { set; get; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Nhập nội dung!")]
        public string MoTa { set; get; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Nhập địa chỉ!")]
        [StringLength(500, ErrorMessage = "Nội dung tối đa 500 kí tự!")]
        public string DiaChi { set; get; }
        [Display(Name = "Khu vực")]
        public string KhuVuc { set; get; }
        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Nhập số điện thoại!")]
        [StringLength(20, ErrorMessage = "Tối đa thiểu 10-20 kí tự!", MinimumLength = 10)]
        public string SDT { set; get; }
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime)]
        public DateTime NgayTao { set; get; }
        [Display(Name = "Lượt thích")]
        public int LuotThich { set; get; }
        [Display(Name = "Link ảnh")]
        [Required(ErrorMessage = "Nhập link ảnh")]
        public string HinhAnh { set; get; }
        [Display(Name="Người đăng")]
        public int UserProfileUserId { set; get; }
        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<BinhLuan> BinhLuans { set; get; }
        public virtual ICollection<ThucDon> ThucDons { set; get; }
        public virtual DanhGia DanhGia { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

Website/Website/Controllers/BinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class BinhLuanController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /BinhLuan/

        public ActionResult Index()
        {
            var binhluans = db.BinhLuans.Include(b => b.DiaDiem);
            return View(binhluans.ToList());
        }

        //
        // GET: /BinhLuan/Details/5

        public ActionResult Details(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Create

        public ActionResult Create()
        {
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten");
            return View();
        }

        //
        // POST: /BinhLuan/Create

        [HttpPost]
        public ActionResult Create(BinhLuan binhluan, int idpost)
        {
            if (ModelState.IsValid)
            {
                binhluan.DiaDiemID = idpost;
                binhluan.NgayTao = DateTime.Now;
                db.BinhLuans.Add(binhluan);
                db.SaveChanges();
                return PartialView("_ViewBinhLuan",binhluan);
                //return RedirectToAction("Details/" + idpost, "DiaDiem");
            }

            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // POST: /BinhLuan/Edit/5

        [HttpPost]
        public ActionResult Edit(BinhLuan binhluan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(binhluan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Delete/5

        public ActionResult Delete(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // POST: /BinhLuan/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            db.BinhLuans.Remove(binhluan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Website/Website/Controllers/DiaDiemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    [Authorize]
    public class DiaDiemController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /DiaDiem/
        public ActionResult Index()
        {
            int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
            var diadiems = db.DiaDiems.Where(d => d.UserProfileUserId==userid).Include(d => d.DanhGia);
            return View(diadiems.ToList());
        }    
        //
        // GET: /DiaDiem/Details/5
        public ActionResult Details(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            ViewData["idpost"] = id;
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID");
            return View();
        }

        //
        // POST: /DiaDiem/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(DiaDiem diadiem,string Content)
        {
            if (ModelState.IsValid)
            {
                diadiem.NgayTao = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                diadiem.UserProfileUserId = userid;
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = Content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag TagExit = null;
                    var ListTag = db.Tags.Where(p => p.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        TagExit = ListTag.First();
                        TagExit.DiaDiems.Add(diadiem);
                    }
                    else
                    {
                        TagExit = new Tag();
                        TagExit.Content = item;
                        TagExit.DiaDiems = new List<DiaDiem>();
                        TagExit.DiaDiems.Add(diadiem);
                    }
                    Tags.Add(TagExit);
                }
                diadiem.Tags = Tags;
                db.DiaDiems.Add(diadiem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // POST: /DiaDiem/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(DiaDiem diadiem)
        {
            if (ModelState.IsValid)
            {
                diadiem.NgayTao = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                diadiem.UserProfileUserId = userid;
                db.Entry(diadiem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            return View(diadiem);
        }

        //
        // POST: /DiaDiem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            db.DiaDiems.Remove(diadiem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Website/Website/Controllers/YeuThichNhatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class YeuThichNhatController : Controller
    {
        private UsersContext db = new UsersContext();
        //
        // GET: /Cafe/

        public ActionResult Index()
        {
            return View();
        }
        //Tim kiem
        [AllowAnonymous]
        public ActionResult Search(string searchString)
        {
            var diadiems = from p in db.DiaDiems select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                diadiems = diadiems.Where(y => y.Tags.Any(t => t.Content.Contains(searchString)));
            }
            return View(diadiems);
        }
        public ActionResult MonAn()
        {
            var ps = (from p in db.DiaDiems
                      where p.ChuDeCon == "Món ăn"
                      orderby p.NgayTao descending
                      select p).Take(5).ToList();
            return View(ps);
        }
        public ActionResult DiaDiem()
        {
            var ps = (from p in db.DiaDiems
                      where p.ChuDeCon == "Địa điểm"
                      orderby p.NgayTao descending
                      select p).Take(5).ToList();
            return View(ps);
        }
        public ActionResult GiaRe()
        {
            var ps = (from p in db.DiaDiems
                      where p.ChuDeCon == "Giá rẻ"
                      orderby p.NgayTao descending
                      select p).Take(5).ToList();
            return View(ps);
        }
        public ActionResult ChiTietDiaDiem(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            ViewData["idpost"] = id;
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(diadiem);
            }
        }
    }
}

Website/Website/Views/YeuThichNhat/ChiTietDiaDiem.cshtml
@model Website.Models.DiaDiem

@{
    ViewBag.Title = "ChiTietDiaDiem";
}

<div class="content">
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","MonAn","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","DiaDiem","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","GiaRe","YeuThichNhat")</a>
    </div>
<div class="hinh">
    <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(model => model.HinhAnh)"width="300" height="300" />
</div>
<div class="noidung">
    <p></p>
    <p>Ngày đăng: @Html.DisplayTextFor(model => model.NgayTao)</p>
       <h2> @Html.DisplayTextFor(model => model.Ten)</h2>
        <p>Địa chỉ :@Html.DisplayTextFor(model => model.DiaChi)</p>
        <p>Số điện thoại :@Html.DisplayTextFor(model => model.SDT)</p>
     <div class="thucdon">
        <div class="menu">
            <ul id="nav">
                <li> 
                    <p style="color: #ff6a00;font-size: 140%;font-weight: bold;"><a class="top-link">Thực đơn</a></p>
                        <div class="down">
                            <div class="menu_down">
                            <p>Tên món</p>
                            @foreach (var g in Model.ThucDons.ToList())
                            {
                                <p>@Html.DisplayTextFor(x => g.TenMon):</p>
                            }
                            </div>
                        <div class="menu_down">
                            <p>Giá</p>
                            @foreach (var h in Model.ThucDons.ToList())
                            {
                                <p>@Html.DisplayTextFor(x => h.Gia) đồng</p>
                            }
                        </div>
                            </div>
                        
                </li>
        </ul>
            </div>
        </div>
</div>
    <div style="text-align:center">
    <h2>Mô tả</h2>
        </div>
    <div style="text-align:justify">
    @Html.DisplayTextFor(model => model.MoTa)
        </div>
@Html.Partial("_ThemBinhLuan",new Website.Models.BinhLuan(),ViewData)
    <fieldset>
    <legend>Bình luận</legend>
    <div id="result">
    @foreach (var Comment in Model.BinhLuans.OrderByDescending(x => x.NgayTao).Take(10))
    {
    <div class="display-field">
        <h3>
        @Html.DisplayFor(x => Comment.NguoiBinhLuan)
        </h3>
    </div>
    <div class="display-field">
        @Html.DisplayFor(x => Comment.NoiDung)
    </div>
         <div class="display-field">
        Cách đây: @Html.DisplayFor(x => Comment.LanCuoi) phút
    </div>
    }
        </div>
</fieldset>
    <fieldset>
    <legend>Tag</legend>
    <div class="post-tags">
        <b>Liên quan:</b>@foreach (var i in Model.Tags)
        {
            <b> @Html.ActionLink(i.Content, "Search", new { searchString = i.Content }) </b>
        }
    </div>
 </fieldset>
</div>

<script src="~/Scripts/ThemBinhLuan.js"></script>

Website/Website/Views/YeuThichNhat/DiaDiem.cshtml
@model IEnumerable<Website.Models.DiaDiem>

@{
    ViewBag.Title = "DiaDiem";
}

<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","MonAn","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","DiaDiem","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","GiaRe","YeuThichNhat")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
        <div class="noidung">
            <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.Ten)</h2>
            </a> 
                <p>Địa chỉ: @Html.DisplayTextFor(modelItem => item.DiaChi)</p>
                <p>Số điện thoại: @Html.DisplayTextFor(modelItem => item.SDT)</p>
        </div>
}

Website/Website/Views/YeuThichNhat/GiaRe.cshtml
@model IEnumerable<Website.Models.DiaDiem>

<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","MonAn","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","DiaDiem","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","GiaRe","YeuThichNhat")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
        <div class="noidung">
            <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.Ten)</h2>
            </a> 
                <p>Địa chỉ: @Html.DisplayTextFor(modelItem => item.DiaChi)</p>
                <p>Số điện thoại: @Html.DisplayTextFor(modelItem => item.SDT)</p>
        </div>
}

Website/Website/Views/YeuThichNhat/Index.cshtml
<link href="~/Content/mystyle.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","Index","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","Index","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","Index","YeuThichNhat")</a>
    </div>

Website/Website/Views/YeuThichNhat/MonAn.cshtml
@model IEnumerable<Website.Models.DiaDiem>

@{
    ViewBag.Title = "MonAn";
}
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","MonAn","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","DiaDiem","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","GiaRe","YeuThichNhat")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
        <div class="noidung">
            <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.Ten)</h2>
            </a> 
                <p>Địa chỉ: @Html.DisplayTextFor(modelItem => item.DiaChi)</p>
                <p>Số điện thoại: @Html.DisplayTextFor(modelItem => item.SDT)</p>
        </div>
}

Website/Website/Views/YeuThichNhat/Search.cshtml
@model IEnumerable<Website.Models.DiaDiem>

@{
    ViewBag.Title = "Search";
}
@Html.Partial("_TimDiaDiem",new Website.Models.DiaDiem(),ViewData)
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Món ăn","MonAn","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Địa điểm","DiaDiem","YeuThichNhat")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Giá rẻ","GiaRe","YeuThichNhat")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
        <div class="noidung">
            <a href="/YeuThichNhat/ChiTietDiaDiem/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.Ten)</h2>
            </a> 
                <p>Địa chỉ: @Html.DisplayTextFor(modelItem => item.DiaChi)</p>
                <p>Số điện thoại: @Html.DisplayTextFor(modelItem => item.SDT)</p>
        </div>
}

Website/Website/Views/YeuThichNhat/_ThemBinhLuan.cshtml
@model Website.Models.BinhLuan


@using (Html.BeginForm("Create", "BinhLuan",FormMethod.Post,new {id = "my-form"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm bình luận</legend>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.NguoiBinhLuan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NguoiBinhLuan)
            @Html.ValidationMessageFor(model => model.NguoiBinhLuan)
        </div>
        @Html.Hidden("idpost",ViewData["idpost"])
        <p>
            <input type="submit" value="Bình luận" />
        </p>
    </fieldset>
}

Website/Website/Views/YeuThichNhat/_TimDiaDiem.cshtml
@model Website.Models.DiaDiem

@using (Html.BeginForm("Search", "YeuThichNhat", FormMethod.Post))
{

    <div>
            Tag: @Html.TextBox("searchString")
            <input type="submit" value="Tìm kiếm" />
        </div>
}