Blog_T6_5/Blog_T6_3/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog_T6_3.Models
{
    public class Post
    {
        [Key]
        public int ID { set; get; }
        [Required(ErrorMessage = "Nhập tiêu đề!")]
        [StringLength(500, ErrorMessage = "Tiêu đề từ 20-500 kí tự!", MinimumLength = 20)]
        public string Title { set; get; }
        [Required(ErrorMessage = "Nhập nội dung!")]
        [StringLength(2000, ErrorMessage = "Nội dung tối thiểu có 50 kí tự!", MinimumLength = 50)]
        public string Body { set; get; }
        [DataType(DataType.DateTime)]
        public DateTime DateCreate { set; get; }
        public int UserProfileUserId { set; get; }
        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
        public virtual ICollection<Comment> Comments { set; get; }
    }
}

Blog_T6_5/Blog_T6_3/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_T6_3.Models;

namespace Blog_T6_3.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        public ActionResult Create(Comment comment,int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DateCreate = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("_ViewContent",comment);
                //return RedirectToAction("Details/"+idpost,"Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_T6_5/Blog_T6_3/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_T6_3.Models;

namespace Blog_T6_3.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile);
            return View(posts.ToList());
        }
        //Search
        [AllowAnonymous]
        public ActionResult Search(string searchString)
        {
            var posts = from p in db.Posts select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(y => y.Tags.Any(t => t.Content.Contains(searchString)));
            }
            return View(posts);
        }
        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["idpost"] = id;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreate = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                //List tag
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = Content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag TagExit = null;
                    var ListTag = db.Tags.Where(p => p.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        TagExit = ListTag.First();
                        TagExit.Posts.Add(post);
                    }
                    else
                    {
                        TagExit = new Tag();
                        TagExit.Content = item;
                        TagExit.Posts = new List<Post>();
                        TagExit.Posts.Add(post);
                    }
                    Tags.Add(TagExit);
                }
                post.Tags = Tags;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_T6_5/Blog_T6_3/Views/Post/Create.cshtml
@model Blog_T6_3.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model =>new Blog_T6_3.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Blog_T6_3.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_T6_5/Blog_T6_3/Views/Post/Delete.cshtml
@model Blog_T6_3.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog_T6_5/Blog_T6_3/Views/Post/Details.cshtml
@model Blog_T6_3.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
<fieldset>
    <legend>Comment</legend>
    <div id="result">
    @foreach (var Comment in Model.Comments.OrderByDescending(x => x.DateCreate).Take(10))
    {
    <div class="display-field">
        <h3>
        @Html.DisplayFor(x => Comment.Author)
        </h3>
    </div>
    <div class="display-field">
        @Html.DisplayFor(x => Comment.Body)
    </div>
         <div class="display-field">
        Cách đây: @Html.DisplayFor(x => Comment.LastTime) phút
    </div>
    }
        </div>
</fieldset>
@Html.Partial("_AddComment",new Blog_T6_3.Models.Comment(),ViewData)
<fieldset>
    <legend>Tag</legend>
    <h2>Tag</h2>
    <div class="post-tags">
        <b>Tags:</b>@foreach (var i in Model.Tags)
        {
            <b> @Html.ActionLink(i.Content, "Search", new { searchString = i.Content }) </b>
        }
    </div>
 </fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog_T6_5/Blog_T6_3/Views/Post/Edit.cshtml
@model Blog_T6_3.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreate)
            @Html.ValidationMessageFor(model => model.DateCreate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileUserId, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserId)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_T6_5/Blog_T6_3/Views/Post/Index.cshtml
@model IEnumerable<Blog_T6_3.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@Html.Partial("_SearchPost", new Blog_T6_3.Models.Post(), ViewData)
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Blog_T6_5/Blog_T6_3/Views/Post/Search.cshtml
@model IEnumerable<Blog_T6_3.Models.Post>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@Html.Partial("_SearchPost", new Blog_T6_3.Models.Post(), ViewData)
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}
</table>

Blog_T6_5/Blog_T6_3/Views/Post/_AddComment.cshtml
@model Blog_T6_3.Models.Comment


@using (Html.BeginForm("Create", "Comment",FormMethod.Post,new {id = "my-form"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>
        <h2>AddComment</h2>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
        @Html.Hidden("idpost",ViewData["idpost"])
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComments.js"></script>

Blog_T6_5/Blog_T6_3/Views/Post/_SearchPost.cshtml
@model Blog_T6_3.Models.Post

@using (Html.BeginForm("Search", "Post", FormMethod.Post))
{

    <fieldset>
    <legend>Search</legend>
        <div>
            Find: @Html.TextBox("searchString")
            <input type="submit" value="Search" />
        </div>
    </fieldset>
}