Website/Website/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class TrangChuController : Controller
    {
        private UsersContext db = new UsersContext();
        //
        // GET: /TrangChu/

        public ActionResult Index()
        {
            ViewBag.View = "";
            return View();
        }
        //Tim kiem
        [AllowAnonymous]
        public ActionResult Search(string searchString)
        {
            var baiviets = from p in db.BaiViets select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                baiviets = baiviets.Where(y => y.Tags.Any(t => t.Content.Contains(searchString)));
            }
            return View(baiviets);
        }
            public ActionResult PhongSuAmThuc()
        {
            var ps = (from p in db.BaiViets 
                     where p.ChuDeCon=="Phóng sự ẩm thực"
                     orderby p.NgayTao descending
                     select p).Take(5).ToList();
                return View(ps);
        }
            public ActionResult MonNgonMoiNgay()
            {
                var ps = (from p in db.BaiViets
                          where p.ChuDeCon == "Món ngon mỗi ngày"
                          orderby p.NgayTao descending
                          select p).Take(5).ToList();
                return View(ps);
            }
            public ActionResult SucKhoe()
            {
                var ps = (from p in db.BaiViets
                          where p.ChuDeCon == "Sức khoẻ"
                          orderby p.NgayTao descending
                          select p).Take(5).ToList();
                return View(ps);
            }
                public ActionResult ChiTiet(int id=0)
            {
                BaiViet baiviet = db.BaiViets.Find(id);
                ViewData["idpostbv"] = id;
                if (baiviet == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(baiviet);
                }
            }
               

    }
}

Website/Website/Views/TrangChu/ChiTiet.cshtml
@model Website.Models.BaiViet

@{
    ViewBag.Title = "ChiTiet";
}

<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Phóng sự ẩm thực","PhongSuAmThuc","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Món ngon mỗi ngày","Index","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Sức khoẻ","Index","TrangChu")</a>
    </div>
<div class="Content">
        Ngày đăng: @Html.DisplayTextFor(model => model.NgayTao)
        <div style="text-align:Center">
            <h2>@Html.DisplayTextFor(model => model.TenBaiViet)</h2>
                </div>
        <div style="text-align:justify">
        @Html.DisplayTextFor(model => model.NoiDung)
            </div>
        <div style="text-align:right">
        @Html.DisplayTextFor(model => model.TacGia)
            </div>
    @Html.Partial("_ThemBinhLuanBaiViet",new Website.Models.BinhLuanBaiViet(),ViewData)
     <fieldset>
    <legend>Bình luận</legend>
    <div id="result">
    @foreach (var Comment in Model.BinhLuanBaiViets.OrderByDescending(x => x.NgayTao).Take(10))
    {
    <div class="display-field">
        <h3>
        @Html.DisplayFor(x => Comment.NguoiBinhLuan)
        </h3>
    </div>
    <div class="display-field">
        @Html.DisplayFor(x => Comment.NoiDung)
    </div>
         <div class="display-field">
        Cách đây: @Html.DisplayFor(x => Comment.LanCuoi) phút
    </div>
    }
        </div>
</fieldset>
    <fieldset>
    <legend></legend>
    <div class="post-tags">
        <b>Liên quan:</b>@foreach (var i in Model.Tags)
        {
            <b> @Html.ActionLink(i.Content, "Search", new { searchString = i.Content }) </b>
        }
    </div>
 </fieldset>
</div>
<script src="~/Scripts/ThemBinhLuanBaiViet.js"></script>

Website/Website/Views/TrangChu/Index.cshtml
<link href="~/Content/mystyle.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}

Website/Website/Views/TrangChu/MonNgonMoiNgay.cshtml
@model IEnumerable<Website.Models.BaiViet>
@{
    ViewBag.Title = "MonNgonMoiNgay";
}

<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Phóng sự ẩm thực","PhongSuAmThuc","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Món ngon mỗi ngày","MonNgonMoiNgay","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Sức khoẻ","SucKhoe","TrangChu")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
    <div class="noidung">
            <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.TenBaiViet)</h2>
            </a> 
                <div style="text-align:justify">
                    <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                    @Html.DisplayTextFor(modelItem => item.NoiDung)
                    </a>
                </div>     
        </div>
}

Website/Website/Views/TrangChu/PhongSuAmThuc.cshtml
@model IEnumerable<Website.Models.BaiViet>

@{
    ViewBag.Title = "PhongSuAmThuc";
}
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Phóng sự ẩm thực","PhongSuAmThuc","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Món ngon mỗi ngày","MonNgonMoiNgay","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Sức khoẻ","SucKhoe","TrangChu")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
    <div class="noidung">
            <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.TenBaiViet)</h2>
            </a> 
                <div style="text-align:justify">
                    <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                    @Html.DisplayTextFor(modelItem => item.NoiDung)
                    </a>
                </div>     
        </div>
}

Website/Website/Views/TrangChu/Search.cshtml
@model IEnumerable<Website.Models.BaiViet>

@{
    ViewBag.Title = "Search";
}
@Html.Partial("_TimBaiViet",new Website.Models.BaiViet(),ViewData)
<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Phóng sự ẩm thực","PhongSuAmThuc","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Món ngon mỗi ngày","Index","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Sức khoẻ","Index","TrangChu")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
    <div class="noidung">
            <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.TenBaiViet)</h2>
            </a> 
                <div style="text-align:justify">
                    <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                    @Html.DisplayTextFor(modelItem => item.NoiDung)
                    </a>
                </div>     
        </div>
}
@Html.Raw(ViewBag.View)

Website/Website/Views/TrangChu/SucKhoe.cshtml
@model IEnumerable<Website.Models.BaiViet>

@{
    ViewBag.Title = "SucKhoe";
}

<div class="danhmuc">
    <a style="color:white">@Html.ActionLink("Phóng sự ẩm thực","PhongSuAmThuc","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Món ngon mỗi ngày","MonNgonMoiNgay","TrangChu")</a><a style="color:white">|</a>
    <a style="color:white">@Html.ActionLink("Sức khoẻ","SucKhoe","TrangChu")</a>
    </div>
@foreach (var item in Model) {
    <div class="hinh">
        <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
            <img style="display: block; margin-left: auto; margin-right: auto;"src="@Html.DisplayTextFor(modelItem => item.HinhAnh)"width="300" height="300" />
        </a>
    </div>
    <div class="noidung">
            <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                <h2>@Html.DisplayTextFor(modelItem=>item.TenBaiViet)</h2>
            </a> 
                <div style="text-align:justify">
                    <a href="/TrangChu/ChiTiet/@Html.DisplayTextFor(modelItem => item.ID)">
                    @Html.DisplayTextFor(modelItem => item.NoiDung)
                    </a>
                </div>     
        </div>
}

Website/Website/Views/TrangChu/_ThemBinhLuanBaiViet.cshtml
@model Website.Models.BinhLuanBaiViet


@using (Html.BeginForm("Create", "BinhLuanBaiViet",FormMethod.Post,new {id = "my-formbv"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm bình luận</legend>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.NguoiBinhLuan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NguoiBinhLuan)
            @Html.ValidationMessageFor(model => model.NguoiBinhLuan)
        </div>
        @Html.Hidden("idpostbv",ViewData["idpostbv"])
        <p>
            <input type="submit" value="Bình luận" />
        </p>
    </fieldset>
}

Website/Website/Views/TrangChu/_TimBaiViet.cshtml
@model Website.Models.BaiViet
@using (Html.BeginForm("Search", "TrangChu", FormMethod.Post))
{
        <div>
            Tag: @Html.TextBox("searchString")
            <input type="submit" value="Tìm kiếm" />
        </div>
}