Website/Website/Models/DiaDiem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Website.Models
{
    public class DiaDiem
    {
        [Key]
        public int ID { set; get; }
        [Display(Name = "Tên địa điểm")]
        [Required(ErrorMessage = "Nhập tên địa điểm!")]
        [StringLength(50, ErrorMessage = "Nội dung tối thiểu 10 kí tự!")]
        public string Ten { set; get; }
        [Display(Name = "Chủ đề")]
        public string ChuDe { set; get; }
        [Display(Name = "Chủ đề con")]
        public string ChuDeCon { set; get; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Nhập nội dung!")]
        public string MoTa { set; get; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Nhập địa chỉ!")]
        [StringLength(500, ErrorMessage = "Nội dung tối đa 500 kí tự!")]
        public string DiaChi { set; get; }
        [Display(Name = "Khu vực")]
        public string KhuVuc { set; get; }
        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Nhập số điện thoại!")]
        [StringLength(20, ErrorMessage = "Tối đa thiểu 10-20 kí tự!", MinimumLength = 10)]
        public string SDT { set; get; }
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime)]
        public DateTime NgayTao { set; get; }
        [Display(Name = "Lượt thích")]
        public int LuotThich { set; get; }
        [Display(Name = "Link ảnh")]
        [Required(ErrorMessage = "Nhập link ảnh")]
        public string HinhAnh { set; get; }
        [Display(Name="Người đăng")]
        public int UserProfileUserId { set; get; }
        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<BinhLuan> BinhLuans { set; get; }
        public virtual ICollection<ThucDon> ThucDons { set; get; }
        public virtual DanhGia DanhGia { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

Website/Website/Controllers/BinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class BinhLuanController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /BinhLuan/

        public ActionResult Index()
        {
            var binhluans = db.BinhLuans.Include(b => b.DiaDiem);
            return View(binhluans.ToList());
        }

        //
        // GET: /BinhLuan/Details/5

        public ActionResult Details(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Create

        public ActionResult Create()
        {
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten");
            return View();
        }

        //
        // POST: /BinhLuan/Create

        [HttpPost]
        public ActionResult Create(BinhLuan binhluan, int idpost)
        {
            if (ModelState.IsValid)
            {
                binhluan.DiaDiemID = idpost;
                binhluan.NgayTao = DateTime.Now;
                db.BinhLuans.Add(binhluan);
                db.SaveChanges();
                return PartialView("_ViewBinhLuan",binhluan);
                //return RedirectToAction("Details/" + idpost, "DiaDiem");
            }

            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // POST: /BinhLuan/Edit/5

        [HttpPost]
        public ActionResult Edit(BinhLuan binhluan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(binhluan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", binhluan.DiaDiemID);
            return View(binhluan);
        }

        //
        // GET: /BinhLuan/Delete/5

        public ActionResult Delete(int id = 0)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // POST: /BinhLuan/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BinhLuan binhluan = db.BinhLuans.Find(id);
            db.BinhLuans.Remove(binhluan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Website/Website/Controllers/DiaDiemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    [Authorize]
    public class DiaDiemController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /DiaDiem/
        public ActionResult Index()
        {
            int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
            var diadiems = db.DiaDiems.Where(d => d.UserProfileUserId==userid).Include(d => d.DanhGia);
            return View(diadiems.ToList());
        }    
        //
        // GET: /DiaDiem/Details/5
        public ActionResult Details(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            ViewData["idpost"] = id;
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID");
            return View();
        }

        //
        // POST: /DiaDiem/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(DiaDiem diadiem,string Content)
        {
            if (ModelState.IsValid)
            {
                diadiem.NgayTao = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                diadiem.UserProfileUserId = userid;
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = Content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag TagExit = null;
                    var ListTag = db.Tags.Where(p => p.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        TagExit = ListTag.First();
                        TagExit.DiaDiems.Add(diadiem);
                    }
                    else
                    {
                        TagExit = new Tag();
                        TagExit.Content = item;
                        TagExit.DiaDiems = new List<DiaDiem>();
                        TagExit.DiaDiems.Add(diadiem);
                    }
                    Tags.Add(TagExit);
                }
                diadiem.Tags = Tags;
                db.DiaDiems.Add(diadiem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // POST: /DiaDiem/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(DiaDiem diadiem)
        {
            if (ModelState.IsValid)
            {
                diadiem.NgayTao = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                diadiem.UserProfileUserId = userid;
                db.Entry(diadiem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", diadiem.UserProfileUserId);
            ViewBag.ID = new SelectList(db.DanhGias, "ID", "ID", diadiem.ID);
            return View(diadiem);
        }

        //
        // GET: /DiaDiem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            if (diadiem == null)
            {
                return HttpNotFound();
            }
            return View(diadiem);
        }

        //
        // POST: /DiaDiem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DiaDiem diadiem = db.DiaDiems.Find(id);
            db.DiaDiems.Remove(diadiem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Website/Website/Controllers/ThucDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class ThucDonController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /ThucDon/

        public ActionResult Index()
        {
            var thucdons = db.ThucDons.Include(t => t.DiaDiem);
            return View(thucdons.ToList());
        }

        //
        // GET: /ThucDon/Details/5

        public ActionResult Details(int id = 0)
        {
            ThucDon thucdon = db.ThucDons.Find(id);
            if (thucdon == null)
            {
                return HttpNotFound();
            }
            return View(thucdon);
        }

        //
        // GET: /ThucDon/Create

        public ActionResult Create()
        {
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten");
            return View();
        }

        //
        // POST: /ThucDon/Create

        [HttpPost]
        public ActionResult Create(ThucDon thucdon,int idpost)
        {
            if (ModelState.IsValid)
            {
                thucdon.DiaDiemID = idpost;
                
                //return RedirectToAction("Details/" + idpost, "DiaDiem");
                db.ThucDons.Add(thucdon);
                db.SaveChanges();
                return PartialView("_ViewThucDon", thucdon);
                //return RedirectToAction("Index");
            }

            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", thucdon.DiaDiemID);
            return View(thucdon);
        }

        //
        // GET: /ThucDon/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ThucDon thucdon = db.ThucDons.Find(id);
            if (thucdon == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", thucdon.DiaDiemID);
            return View(thucdon);
        }

        //
        // POST: /ThucDon/Edit/5

        [HttpPost]
        public ActionResult Edit(ThucDon thucdon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thucdon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiaDiemID = new SelectList(db.DiaDiems, "ID", "Ten", thucdon.DiaDiemID);
            return View(thucdon);
        }

        //
        // GET: /ThucDon/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ThucDon thucdon = db.ThucDons.Find(id);
            if (thucdon == null)
            {
                return HttpNotFound();
            }
            return View(thucdon);
        }

        //
        // POST: /ThucDon/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ThucDon thucdon = db.ThucDons.Find(id);
            db.ThucDons.Remove(thucdon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Website/Website/Views/DiaDiem/Create.cshtml
<script src="~/Content/ckeditor/ckeditor.js"></script>
<script src="~/Content/ckfinder/ckfinder.js"></script>
<script type="text/javascript">
    $(function () {
        $("#Browser").click(function () {
            var ckfinder = new CKFinder();
            ckfinder.selectActionFunction = function (fileUrl) {
                $("#Images").val(fileUrl)
            };
            ckfinder.popup();
        });
    });
</script>
@model Website.Models.DiaDiem

@{
    ViewBag.Title = "Create";
}

<h2>Thêm địa điểm mới</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Địa điểm</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Ten)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ten)
            @Html.ValidationMessageFor(model => model.Ten)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChuDe)
        </div>
        <div class="editor-field">
            <div class="editor-field">
            @Html.DropDownList("ChuDe",new SelectList(new []{"Trang chủ","Cafe","Nhà hàng","Quán bình dân","Yêu thích nhất","Gợi ý"}))
            @Html.ValidationMessageFor(model => model.ChuDe)
        </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChuDeCon)
        </div>
        <div class="editor-field">
            @Html.DropDownList("ChuDeCon",
            new SelectList(new []{"Phóng sự ẩm thực","Món ngon mỗi ngày","Sức khoẻ",
            "Cafe","Kem","Phòng Trà",
            "Nhà hàng tiệc cưới","Nhà hàng Á","Nhà hàng Âu",
            "Quán cơm","Quán nhậu","Ăn vặt",
            "Món ăn","Địa điểm","Giá rẻ",
            "Gợi ý"}))
            @Html.ValidationMessageFor(model => model.ChuDeCon)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MoTa)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.MoTa, new { @id="NoiDung"})
            <script type="text/javascript">
                CKEDITOR.replace("NoiDung");
            </script>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DiaChi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DiaChi)
            @Html.ValidationMessageFor(model => model.DiaChi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.KhuVuc)
        </div>
        <div class="editor-field">
            @Html.DropDownList("KhuVuc",new SelectList(new []{"Quận 1","Quận 2","Quận 3","Quận 4","Quận 5","Quận 6","Quận 7","Quận 8","Quận 9","Quận 10","Quận 11","Quận 12","Quận Thủ Đức","Quận Gò Vấp","Quận Bình Thạnh","Quận Tân Bình","Quận Tân Phú","Quận Phú Nhuận","Quận Bình Tân"}))
            @Html.ValidationMessageFor(model => model.KhuVuc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SDT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDT)
            @Html.ValidationMessageFor(model => model.SDT)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.HinhAnh)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.HinhAnh, new { @id="Images"})
            <input id="Browser" type="button" value="Chọn ảnh" />
        </div>
        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model =>new Website.Models.Tag().Content)
            @Html.ValidationMessageFor(model =>new Website.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Thêm địa điểm" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Website/Website/Views/DiaDiem/Delete.cshtml
@model Website.Models.DiaDiem

@{
    ViewBag.Title = "Delete";
}

<h2>Xoá</h2>

<h3>Bạn có muốn xoá?</h3>
<fieldset>
    <legend>DiaDiem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ten)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ten)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDeCon)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDeCon)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MoTa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MoTa)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DiaChi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DiaChi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.KhuVuc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.KhuVuc)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SDT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SDT)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayTao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayTao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LuotThich)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LuotThich)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.HinhAnh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HinhAnh)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Xoá" /> |
        @Html.ActionLink("Trở về danh sách", "Index")
    </p>
}

Website/Website/Views/DiaDiem/Details.cshtml
@model Website.Models.DiaDiem

@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết địa điểm</h2>

<fieldset>
    <legend>Địa điểm</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ten)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ten)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDeCon)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDeCon)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MoTa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MoTa)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DiaChi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DiaChi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.KhuVuc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.KhuVuc)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SDT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SDT)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayTao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayTao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LuotThich)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LuotThich)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.HinhAnh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HinhAnh)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
    <fieldset>
<legend>Thực đơn</legend>
    <div id="result1">
    @foreach (var Comment in Model.ThucDons.ToList())
    {
    <p><a>Món</a> <a>@Html.DisplayTextFor(x => Comment.TenMon)</a>  <a>:</a><a> @Html.DisplayTextFor(x => Comment.Gia) đồng</a> </p>
    }
        </div>
</fieldset>
@Html.Partial("_ThemThucDon",new Website.Models.ThucDon(),ViewData)
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Trở về danh sách", "Index")
</p>
<script src="~/Scripts/ThemThucDon.js"></script>

Website/Website/Views/DiaDiem/Index.cshtml
@model IEnumerable<Website.Models.DiaDiem>

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách</h2>

<p>
    @Html.ActionLink("Thêm mới địa điểm", "Create")
</p>
<table border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ten)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChuDeCon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KhuVuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayTao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LuotThich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ten)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChuDeCon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KhuVuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayTao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LuotThich)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Chi tiết", "Details", new { id=item.ID }) |
            @Html.ActionLink("Xoá", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Website/Website/Views/DiaDiem/_ThemBinhLuan.cshtml
@model Website.Models.BinhLuan


@using (Html.BeginForm("Create", "BinhLuan",FormMethod.Post,new {id = "my-form"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm bình luận</legend>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.NguoiBinhLuan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NguoiBinhLuan)
            @Html.ValidationMessageFor(model => model.NguoiBinhLuan)
        </div>
        @Html.Hidden("idpost",ViewData["idpost"])
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComments.js"></script>

Website/Website/Views/DiaDiem/_ThemThucDon.cshtml
@model Website.Models.ThucDon

@using (Html.BeginForm("Create", "ThucDon", FormMethod.Post, new { id = "my-formtd" })) 
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm thực đơn</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenMon)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenMon)
            @Html.ValidationMessageFor(model => model.TenMon)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Gia)
            @Html.ValidationMessageFor(model => model.Gia)
        </div>
         @Html.Hidden("idpost",ViewData["idpost"])
        <p>
            <input type="submit" value="Thêm món" />
        </p>
    </fieldset>
}

Website/Website/Views/DiaDiem/_TimDiaDiem.cshtml
@model Website.Models.DiaDiem

@using (Html.BeginForm("Search", "DiaDiem", FormMethod.Post))
{

    <fieldset>
    <legend>Tìm kiếm</legend>
        <div>
            Tìm kiếm: @Html.TextBox("searchString")
            <input type="submit" value="Search" />
        </div>
    </fieldset>
}